### ISSUE TITLE
Testing / Examples: Improvement

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/md2pptx#10]
Add example files for testing and learning how to use the features.

(Maybe even a combined one with mdpre)

**Comment by MartinPacker** [comment]
Agree. I now have a test subdir. Will make sure it's there. Then think about adding some examples.

**Comment by MartinPacker** [comment]
See fullPresentation.* for an example. Note: It uses `<span>` for colour effects. You'd need to supply the CSS if converting to HTML but it works fine with md2pptx.

**Comment by MartinPacker** [comment]
See twoGraphics.* for a graphics-related example. Note: I had to copy Martin Master.pptx into /test to make it work.

**Comment by 42sol-eu** [comment]
cool
