### ISSUE TITLE
Slide notes contain code blocks

### ISSUE THREAD

**Issue by scottballentine** [MartinPacker/md2pptx#104]
When adding a code block using the `<code>`...`</code>` tags, the blocks (including the tags) also show up in the slide notes.

Also happens with `<pre>`.  Didn't try triple backticks, but I assume it also behaves the same way.

**Comment by MartinPacker** [comment]
Triple backticks indeed show the same bug.

**Comment by MartinPacker** [comment]
Also subtitle of a title slide.

**Comment by MartinPacker** [comment]
Fixed in v2.4.1.

The "Adding Notes Slides" section is worth a re-read - if you use slide notes. In particular, it points out you can intersperse eg code blocks and explanatory notes.
