### ISSUE TITLE
Improve Path Handling (winOS)

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/md2pptx#11]
`slideMasterFile` is checked for a path seperator (`/`) which is linux and macOS only.
Windows (winOS) sadly uses `\`.

Using the `pathlib.Path` object from standard library solves that issue completly.

```python
if slideMasterFile != "":
    from pathlib import Path # move this to top of script obviusly
    if not Path(slideMasterFile).exits():
        # Slide master in same directory as md2pptx code
        script_path = Path(".")
        slideMasterFile = script_path / slideMasterFile
    print(f"\nUsing {slideMasterFile} as base for presentation")
```

**Comment by MartinPacker** [comment]
I think that's `exists()` rather than `exits()` and fixed accordingly. It seems to work.

My fix also assumes Python3 as pathlib isn't in Python 2. I will need to update the documentation on that point.
