### ISSUE TITLE
how to integrate by code

### ISSUE THREAD

**Issue by shaojun** [MartinPacker/md2pptx#144]
Thanks for the great work, any guidiance for integrate the feature via python code?

**Comment by shaojun** [comment]
i developed a Python application that want to call your function in code(by import your library as a module) rather than command line

**Comment by MartinPacker** [comment]
I think you can use a Python command to run a command line invocation. Might be something like `sys.exec`. You can probably redirect input and output also.

Closing for now but feel free to reopen.
