### ISSUE TITLE
Is there any tutorial on converting ppt to markdown language, besides examples?

### ISSUE THREAD

**Issue by Bruce337f** [MartinPacker/md2pptx#145]
I tried to convert ppt to markdown language through python-pptx, but the converted result has no effect on md2pptx. How can I prefetch results similar to the markdown example you gave? Any good ideas?

And can it retain the original format, such as font style, size, position, etc.?

This is a **good project**! !

**Comment by MartinPacker** [comment]
Hi. Thanks for your kind words.

Unfortunately md2pptx doesn't do what I think you're looking for:

1. It doesn't deal with .ppt at all (only .pptx).
2. It doesn't convert **from** .pptx **to** Markdown. It's the other way round: Generating .pptx from Markdown.

I don't expect it to ever do either of these. It **is** perhaps feasible to write a python-pptx script to extract elements from a .pptx file and convert some of them to Markdown format. But I don't intend this project to do that.
