### ISSUE TITLE
Is it possible to read the image in an adjustable manner？

### ISSUE THREAD

**Issue by Bruce337f** [MartinPacker/md2pptx#146]
For example: the image with the general characters on the right side and middle, and the unenclosed image covered?
I have tried by using HTML and CSS to create a container with images and text, and using CSS styles to set the layout, but it doesn't work, any suggestions?
_div style="display: flex; align-items: center;">
  img src="image.jpg" alt="img" style="max-width: 50%; margin-right: 20px;"
  div>
    p>text</p>
  /div>
/div>_

**Comment by MartinPacker** [comment]
One possibility - which ignores Problem 1 - is to have a metadata item that says how the graphic should behave. It would still leave Problem 2 and quite a lot of code would be needed.

**Comment by MartinPacker** [comment]
Further to that idea, it could be "dynamic metadata", meaning you could set it at any point for all subsequent slides.

But, still, the main problem is how to tweak the XML so that Powerpoint shows the behaviour.

**Comment by MartinPacker** [comment]
Thanks for your kind words.

The CSS support you see in md2pptx is actually in **my** parser, not python-pptx. It is very limited and its purpose **today** is to support colours when rendered by other Markdown processors. Supporting more CSS is possible - but not as complex as the fragment you've shown.

I'm more optimistic than you about panning and zoom...

... If you can demonstrate that a .pptx can contain this functionality **without resorting to VBA** it's highly likely the necessary XML can be crafted by md2pptx. So please try to create an example and - add here instructions to recreate.

If we get that far I think we can do this with a metadata item. And if md2pptx can do it with metadata it could certainly do it with **dynamic** metadata. The implications of that are one slide could pan and zoom and others could scale.

**Comment by MartinPacker** [comment]
So the image background normally comes from the template pptx. Unless you mean a different image on every slide. md2pptx doesn't add background images.

The code you posted - with interesting comments 😃 - just creates a static picture on a slide (if it even works).

Maybe you don't want pan and zoom after all.

**Comment by MartinPacker** [comment]
I did a little research and it doesn't look like Powerpoint has a pan and zoom capability. Its only option for images is scaling.

**Comment by MartinPacker** [comment]
Several things here:

Markdown doesn't have a standard way of doing a background. md2pptx could add one - as it's just an image. If you need that open an issue. The mechanism for page-by-page background images would be (dynamic) metadata. Whether this is just an image composed onto the page or a true background depends on research into the XML.

I've had the request for a package before. I'll have to think about how to do it.

On the "colours" question, it's in the theme the template uses. And where they are used are again down to how the template is set up. Choose / make your template carefully. For example, the built in template for python-pptx is not very modern. The example one in md2pptx is much better, in my opinion.
