### ISSUE TITLE
DISCUSSION: Effects during Template Creation

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/md2pptx#15]
Hi Martin,
during Template Creation (modifying your "Martin Template.pptx" to my templates) 
I have some questions that I do not understand.

If you have a quick idea its fine, but I will investigate the other stuff anyway.

- [ ] Font Overwrite: The font sometimes ignores the defined settings in the master-slide
- [ ] Text Position Overwrite in Heading Slide (Level `##`): The textbox will be moved to your template position even if it takes my settings 
- [ ] Table-Seperator still showing in pptx

![image](https://user-images.githubusercontent.com/19718152/96063157-9e15a000-0e97-11eb-8c6e-21be7a17c4ec.png)

**Comment by 42sol-eu** [comment]
Zum Table-Seperator: Commandozeile meldet `   5     Percentile Goal Transaction Ending Buckets             --> 16 x 4 table without heading`

**Comment by MartinPacker** [comment]
Let me just comment on the separator line. It looks like it’s not being recognised as the second line so not being used to align things or set widths.

Can you send me a snippet showing what the beginning of the table looks like?

Note: The width thing is not standard Markdown Tables semantic. (It’s fine syntax-wise.)

**Comment by 42sol-eu** [comment]
yep. I will send it from my windows machine once that is running again

**Comment by MartinPacker** [comment]
Is your Windows machine running again? ... :-)

**Comment by MartinPacker** [comment]
Closing for now. Reopen if needed.
