### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by ljn12yyds** [MartinPacker/md2pptx#155]
![image](https://github.com/MartinPacker/md2pptx/assets/155718919/8f38c287-a2c5-4876-b851-5a36269192ab)

**Comment by MartinPacker** [comment]
It has to be installed and on the path. If it's not on the path you'd need to do something like `~/md2pptx/md2pptx file.pptx < file.md`.

**Comment by MartinPacker** [comment]
I'm assuming this handled the original issue. Closing.
