### ISSUE TITLE
Special Title Data

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/md2pptx#16]
Hi,
my template has a two row title layout.
I would love to set the first row to a text (like the section title)
and the second row to the slides title.

Would this be possible in the given structure of the md2pptx?

**Comment by MartinPacker** [comment]
The question is “how would you code this in Markdown?”

Today I use `<br/>` to separate the two lines - on quite a lot of my slides. Does that help?

**Comment by 42sol-eu** [comment]
It should work.

The original slide template has two boxes with different formating (color and bold) but I see that it is easyier with one box and formatting.


# Extending the question 

Does mdpre give me variables or even the active parent section heading to generate a structure like:

```
## Part 1: Accessing The Train
### Materials
### Setup
### Tipps
```

and generate output like:

```
### ** <span class="blue"> Part 1: Accessibg The Train**</span>\n
Materials 
```

That would be fabolus.

**Comment by MartinPacker** [comment]
mdpre has variables. Also conditional processing. And you want a newline before "Materials" so md2pptx would achieve that if you code `<br/>` (an HTML line break.)

mdpre could generate that line break.

The lack of blank lines between Materials and Setup and Tipps worries me as there is no content in any of those slides. I'm not even sure those slides would get generated.

So, first code up what md2pptx should process and show it to me. Use the `<br/>` for a line break in the title. Then we can figure out what mdpre should be asked to do.

**Comment by MartinPacker** [comment]
I just checked the md2pptx manual and it has the following line:

> To force a line break code `<br/>`.

**Comment by MartinPacker** [comment]
How about using Heading Level 4 for the subtitle of a slide? Would become a second line with an implicit <br/>.

That's not too far from the intent of Heading Level 4 in Markdown.

**Comment by MartinPacker** [comment]
Nothing to do here, I think. Closing.
