### ISSUE TITLE
Handle Binary Files (images and more)

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/md2pptx#23]
- [ ] TODO:elaborate [Andreas,Martin]

**Comment by MartinPacker** [comment]
A data: URL for images might be nice. So far I’ve only worked on Mac so that hasn’t been needed.

**Comment by MartinPacker** [comment]
I'm wondering what Markdown would do with binary files.

**Comment by 42sol-eu** [comment]
During writing the how to hide links in Drafts thread is was wondering if it might be a crazy idea to store the filmendem as a title and putter binary data to the content in Drafts. But URLs should be the main choice.

**Comment by MartinPacker** [comment]
I don't understand your last comment. What I'm thinking of is to allow URLs as image sources, including `data:` URLs. This has two positive effects:

1. Allows you to build a presentation from a remote server, including stock images.
2. Allows you to keep image `data:` URLs in your eg Drafts draft, perhaps as some kind of transclusion.

I think a combination of StringIO and urllib could get us there.

**Comment by MartinPacker** [comment]
data: URL added a while back.
