### ISSUE TITLE
Include other Drafts drafts

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/md2pptx#24]
- [ ] TODO:elaborate [Andreas,Martin]

- [ ] Create a Java Script based action to include other drafts and saving it as a [[title]].mdp in file location accessible by Pytho

**Comment by MartinPacker** [comment]
How is this different from mdpre?

**Comment by 42sol-eu** [comment]
Iwans wondering if wewould have to export envy linked draft that is `=include`d as a file or gather them in Drafts first.

**Comment by MartinPacker** [comment]
Yes. They have to end up in a real file. An action to either:

1) Transclude the drafts in Drafts.

or

2) Export and create the =include statements

would be handy.

Actually I favour Option 1) as generating meaningful names and placing the files somewhere is tough.

Note: The rest of mdpre is valuable eg CSV to Table and variable definition.

**Comment by MartinPacker** [comment]
Closing. Can reopen.
