### ISSUE TITLE
add py extension on script

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/md2pptx#6]
or add a second script with extension to use and edit it on iOS (Working Copy, Pythonista and Pyto)

**Comment by MartinPacker** [comment]
What would be the mechanism? Could the .py call the one without the extension?

And I assume just suggesting people rename is not workable.

**Comment by 42sol-eu** [comment]
maybe look the topic from the different angle. what your not using the extension for the script is aiming at is a command-line tool (executable) this could be done if you use the standard library setuptools feature like described in https://click.palletsprojects.com/en/7.x/setuptools/#setuptools-integration

**Comment by MartinPacker** [comment]
I just added a symlink, committed, and pushed. Does that work?

**Comment by 42sol-eu** [comment]
No. 
- Pyto does crash
- Pythonista recogizes the link but will not start the md2pptx

Could we change the logic (md2pptx as a softlink) on the .py file?

**Comment by MartinPacker** [comment]
Yes. We could do it that way round.

**Comment by 42sol-eu** [comment]
https://github.com/MartinPacker/md2pptx/pull/21

**Comment by 42sol-eu** [comment]
Look at this https://actions.getdrafts.com/a/1dd

**Comment by MartinPacker** [comment]
That looks good! Obviously we need to generalise from fullPresentation.md and I have to wonder how we handle graphics.

**Comment by MartinPacker** [comment]
I also need some doc - in the README (perhaps) and User Guide - definitely.

Unless you’re adept with mdpre it’s probably best not to edit the .mdp file but send me the words instead. Thanks!

**Comment by 42sol-eu** [comment]
Sure Thing
I will do it that way

**Comment by MartinPacker** [comment]
I think this was done a while back. Closing. Please reopen if not.
