### ISSUE TITLE
hipodz.pptx missing

### ISSUE THREAD

**Issue by mikegilchrist** [MartinPacker/md2pptx#65]
I'm having a problem with a missing template "hipodz.pptx" and I can't find it on the webbernet.

Running
```
$ md2pptx test/cardTest.md /tmp/cardTest.pptx

md2pptx Markdown To Powerpoint Converter 1.8.1 10 February, 2021
================================================================
Open source project: https://github.com/MartinPacker/md2pptx

Metadata:
=========

Name                                     Value
----                                     -----
template                                 Martin Template.pptx
template                                 hipodz.pptx
cardlayout                               horizontal
baseTextSize                             20
CardColour                               BACKGROUND 2
CardTitlePosition                        inside
cardshadow                               yes
cardshape                                rounded

Template file hipodz.pptx does not exist. Terminating.

```
Commenting out the corresponding template line in cardTest.md fixes the problem.

**Comment by MartinPacker** [comment]
Ah. I'm sorry about that. That's our internal template file. Please use the one I **did** include: Martin Template.pptx . And then evolve your own - if you want to.

I will keep this issue open until I fix cardTest.md to point to Martin Template.pptx .

**Comment by MartinPacker** [comment]
Ah. I see what I did: Deleting the "hipodz" line will work. As should swapping the 2 template metadata lines round.

But I'll fix today.

**Comment by MartinPacker** [comment]
Fixed. And now the built presentation is include in the test subfolder.
