### ISSUE TITLE
Option to generate ODP

### ISSUE THREAD

**Issue by yamsu** [MartinPacker/md2pptx#81]
This is a wonderful tool to generate pptx. If there can be an option to make to opd, libreoffice impress. Python odpdown module already exists and is somewhat similar to python pptx module.

**Comment by MartinPacker** [comment]
Thank you @yamsu for raising this. It caused me to think about how to create an ODP. md2pptx is an extensive user of python-pptx. Replacing those calls with calls to something else would be difficult.

I believe Libre Office (and OpenOffice) can directly read pptx files. That's probably the best way forward - but please do check I'm right.

**Comment by MartinPacker** [comment]
You didn't come back on this so I'm assuming (and hoping) it's OK to close. So closing with "Wont Fix".

**Comment by yamsu** [comment]
Apologies, I missed your post. This is not critical!
Yes libreoffice does support both pptx and ODP and can convert between the two formats.
