### ISSUE TITLE
Code blocks appear to show up in speaker notes

### ISSUE THREAD

**Issue by scottballentine** [MartinPacker/md2pptx#88]
It looks like code blocks show up on the slide as well as in the slide notes.  (I tried triple backticks and code, but not pre.)
Not positive, but it might be that the notes section sees them as notes (since there's no bullet/list/etc.).  The code tags also come through in the slide notes.

**Comment by MartinPacker** [comment]
Thanks for a good bug report. The clue that the tags are also presented is an important one, I think.

**Comment by MartinPacker** [comment]
Fixed for everything other than subtitles on title and section slides - which present their own difficulties.

**Comment by MartinPacker** [comment]
Fixed for subtitles, also.

Shipped in v2.2.4.
